### ISSUE TITLE
Test failed with Ruby 2.7

### ISSUE THREAD

**Issue by hsbt** [k-tsj/power_assert#30] opened 2019-08-10 21:43 UTC
dyna_symbol_key_test.rb was failed with Ruby 2.7.

```
F
================================================================================================================================================================
     18:   end
     19:
     20:   t do
  => 21:     assert_equal <<END.chomp, assertion_message {
     22:       {"a": 1.to_s}.nil?
     23:               |     |
     24:               |     false
/Users/hsbt/Documents/github.com/k-tsj/power_assert/test/dyna_symbol_key_test.rb:21:in `block in <class:TestDynaSymbolKey>'
<"      {\"a\": 1.to_s}.nil?\n" +
"              |     |\n" +
"              |     false\n" +
"              \"1\""> expected but was
<"      {\"a\": 1.to_s}.nil?\n" + "              |\n" + "              \"1\"">

diff:
        {"a": 1.to_s}.nil?
?               |     |
-               |     false
                "1"
Failure: test: /Users/hsbt/Documents/github.com/k-tsj/power_assert/test/dyna_symbol_key_test.rb --location 20 (TestDynaSymbolKey)
```

I'm not sure why it's happened. I found this fail with `make test-bundled-gems`: https://github.com/ruby/ruby/pull/2336/checks

```
$ ruby -v
ruby 2.7.0dev (2019-08-10T05:38:30Z master d69ffa4d93) +JIT [x86_64-darwin18]
```

**Comment by k-tsj** [comment] 2019-08-11 02:03
Thanks for reporting. I've fixed by 23b2310b7fafe53f235f872b58fb2baad3ea2ff5.

This failure was caused by opt_nil_p, a new VM instruction in Ruby 2.7.

**Closed by k-tsj** 2019-08-11 02:03 UTC
